/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_corristo_eclipse_powerdetect_NativeInterop */

#ifndef _powersrc_h
#define _powersrc_h
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *, void *);

/*
 * Class:     ru_corristo_eclipse_powerdetect_NativeInterop
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_corristo_eclipse_powerdetect_PowerSourceDetector_initialize
  (JNIEnv *, jclass);

/*
 * Class:     ru_corristo_eclipse_powerdetect_NativeInterop
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_corristo_eclipse_powerdetect_PowerSourceDetector_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
